# Configuration for cargo-release
# https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

# Pre-release checks and hooks
pre-release-replacements = [
  # Update version in README.md installation instructions if present
  {file="README.md", search="worktree-bin/[0-9]+\\.[0-9]+\\.[0-9]+", replace="worktree-bin/{{version}}", exactly=0},
]

# Quality assurance hooks before release
pre-release-hook = [
  "cargo fmt --check",
  "cargo clippy --all-targets --all-features -- -D warnings", 
  "cargo test",
  "cargo build --release"
]

# Git configuration
tag-message = "Release {{crate_name}} v{{version}}"
tag-prefix = "v"
tag-name = "v{{version}}"

# Commit configuration  
tag = true
push = true
sign-commit = false
sign-tag = false

# Release commit message
pre-release-commit-message = "Release v{{version}}"

# Don't publish automatically - requires manual confirmation
publish = false

# Verify the contents look right before publishing
verify = true